### ISSUE TITLE
backend read API definition

### ISSUE THREAD

**Issue by alexamici** [bopen/xarray#4]
Currently:

* Store returns `xr.Variable`’s, dataset `attributes` and `encodings`
* *xarray* applies all default filters (netCDF specific) to all backends before building the `xr.Dataset`

Proposal 1:
* Store returns `xr.Variable`’s and the list of filters to be applied to every variable, dataset `attributes` and `encodings`
* *xarray* applies to every variable only the filters selected by the backend before building the `xr.Dataset`

Proposal 2:
* Store returns `xr.Variable`’s with all needed filters applied (configured by *xarray*), dataset `attributes` and `encodings`
* *xarray* builds the `xr.Dataset`

At the moment backends are expected to return variables equivalent to non-decoded netCDF ones, so for example *cfgrib* needs to duplicate make time variables.

Optional:
* post-process filters to be applied on the `xr.Dataset`. In the case of *cfgrib* that would select the naming / units conventions (`cf2cdm` inside *cfgrib*)

Open questions:
* list of backend / data types that do not fit the current model.
* any change to the handing of `BackendArray`?

**Comment by aurghs** [comment]
Pros and cons from my point of view.

**Proposal 1**

**Considerations**:
We could decide that all the filters that the user can disable should be applied by xarray, so all the enable and disable could be managed by xarray. 
**pros**:
- The backend is free to decide which representation to provide.
- More control on the backend  (not necessary, the backend can decide to apply all the filters internally and provide xarray and empty list of filters to be applied)
- enable / disable filters logic would be in xarray?
- all the filters would have the same interface. 
- registered filters could be used by other backends?

**cons**:
- Confusing backend-xarray interface
- More difficult to define interfaces. More conflicts (registered filters with the same name...?).
- Need more structure to define this interface, more code to maintain.

**Proposal 2**

**pros**:
- interface backend-xarray is more clear / backend and xarray has well different defined tasks.
- interface would be minimal and easier to be implemented
- No intermediate representations
- Less code to maintain

**cons**:
- less control on filters.
- more complex explicit definition of the interface (every filter must understand what `decode_times` means in their case)
- more complexity inside the filters


**Let’s start for now with the second one**
